<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>LaraGYM</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />

    @vite(['resources/css/app.css', 'resources/css/burgir.css', 'resources/js/app.js', 'resources/js/burgir.js'])

</head>

<body>

    {{-- Hero section  --}}
    <x-header/>

    {{-- Navigation section --}}
    <x-navigation/>

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas dui id ornare arcu odio ut sem nulla. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Nec dui nunc mattis enim ut tellus elementum sagittis. Est placerat in egestas erat imperdiet sed euismod nisi porta. Donec ac odio tempor orci dapibus. Condimentum vitae sapien pellentesque habitant morbi. Eget nulla facilisi etiam dignissim diam quis enim. Morbi tincidunt ornare massa eget egestas. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Condimentum lacinia quis vel eros donec ac odio. Id semper risus in hendrerit gravida. Quam elementum pulvinar etiam non. Diam sollicitudin tempor id eu. Consequat mauris nunc congue nisi vitae suscipit tellus. Convallis a cras semper auctor neque vitae. Pharetra sit amet aliquam id diam. Tortor id aliquet lectus proin nibh nisl condimentum.

Lacinia at quis risus sed vulputate odio. Nunc sed velit dignissim sodales ut eu sem integer vitae. Purus viverra accumsan in nisl nisi scelerisque eu. Rhoncus aenean vel elit scelerisque. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Augue neque gravida in fermentum et. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Vel eros donec ac odio tempor orci dapibus. Quisque sagittis purus sit amet volutpat consequat mauris. Sit amet luctus venenatis lectus. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Nisl condimentum id venenatis a condimentum. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Commodo sed egestas egestas fringilla. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Sagittis vitae et leo duis ut. Elementum integer enim neque volutpat ac tincidunt vitae semper quis.

Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Mi proin sed libero enim sed faucibus turpis. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Condimentum mattis pellentesque id nibh. Condimentum lacinia quis vel eros donec ac odio tempor orci. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Dignissim diam quis enim lobortis. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Velit euismod in pellentesque massa placerat duis ultricies lacus. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Risus pretium quam vulputate dignissim suspendisse in. Quam id leo in vitae. Amet massa vitae tortor condimentum. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Leo duis ut diam quam nulla. A pellentesque sit amet porttitor eget dolor morbi. Ullamcorper dignissim cras tincidunt lobortis. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Convallis convallis tellus id interdum velit laoreet.

Aliquam vestibulum morbi blandit cursus risus at. Sed pulvinar proin gravida hendrerit lectus. Ac placerat vestibulum lectus mauris ultrices eros in. Sed euismod nisi porta lorem mollis aliquam. Proin fermentum leo vel orci porta non. Morbi tristique senectus et netus. In ornare quam viverra orci sagittis eu volutpat. At varius vel pharetra vel turpis. Ut pharetra sit amet aliquam id diam maecenas. Aliquam nulla facilisi cras fermentum odio eu. Ut venenatis tellus in metus. Mattis enim ut tellus elementum sagittis vitae et. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Eu nisl nunc mi ipsum faucibus vitae aliquet. Egestas sed tempus urna et pharetra. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Dictum varius duis at consectetur lorem donec massa sapien. Faucibus nisl tincidunt eget nullam.

Nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Sit amet consectetur adipiscing elit pellentesque. Lobortis mattis aliquam faucibus purus in massa tempor nec. Tellus in metus vulputate eu scelerisque. Integer eget aliquet nibh praesent tristique magna sit amet. Tortor at auctor urna nunc id. Aenean vel elit scelerisque mauris. Eleifend donec pretium vulputate sapien nec sagittis. Semper quis lectus nulla at. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Sit amet porttitor eget dolor morbi.

Donec pretium vulputate sapien nec sagittis. Arcu bibendum at varius vel. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Nunc lobortis mattis aliquam faucibus purus. Eget mauris pharetra et ultrices neque ornare aenean euismod. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. In hendrerit gravida rutrum quisque non tellus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Tincidunt eget nullam non nisi est sit amet facilisis magna. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Quis viverra nibh cras pulvinar mattis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas dui id ornare arcu odio ut sem nulla. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Nec dui nunc mattis enim ut tellus elementum sagittis. Est placerat in egestas erat imperdiet sed euismod nisi porta. Donec ac odio tempor orci dapibus. Condimentum vitae sapien pellentesque habitant morbi. Eget nulla facilisi etiam dignissim diam quis enim. Morbi tincidunt ornare massa eget egestas. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Condimentum lacinia quis vel eros donec ac odio. Id semper risus in hendrerit gravida. Quam elementum pulvinar etiam non. Diam sollicitudin tempor id eu. Consequat mauris nunc congue nisi vitae suscipit tellus. Convallis a cras semper auctor neque vitae. Pharetra sit amet aliquam id diam. Tortor id aliquet lectus proin nibh nisl condimentum.

Lacinia at quis risus sed vulputate odio. Nunc sed velit dignissim sodales ut eu sem integer vitae. Purus viverra accumsan in nisl nisi scelerisque eu. Rhoncus aenean vel elit scelerisque. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Augue neque gravida in fermentum et. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Vel eros donec ac odio tempor orci dapibus. Quisque sagittis purus sit amet volutpat consequat mauris. Sit amet luctus venenatis lectus. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Nisl condimentum id venenatis a condimentum. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Commodo sed egestas egestas fringilla. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Sagittis vitae et leo duis ut. Elementum integer enim neque volutpat ac tincidunt vitae semper quis.

Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Mi proin sed libero enim sed faucibus turpis. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Condimentum mattis pellentesque id nibh. Condimentum lacinia quis vel eros donec ac odio tempor orci. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Dignissim diam quis enim lobortis. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Velit euismod in pellentesque massa placerat duis ultricies lacus. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Risus pretium quam vulputate dignissim suspendisse in. Quam id leo in vitae. Amet massa vitae tortor condimentum. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Leo duis ut diam quam nulla. A pellentesque sit amet porttitor eget dolor morbi. Ullamcorper dignissim cras tincidunt lobortis. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Convallis convallis tellus id interdum velit laoreet.

Aliquam vestibulum morbi blandit cursus risus at. Sed pulvinar proin gravida hendrerit lectus. Ac placerat vestibulum lectus mauris ultrices eros in. Sed euismod nisi porta lorem mollis aliquam. Proin fermentum leo vel orci porta non. Morbi tristique senectus et netus. In ornare quam viverra orci sagittis eu volutpat. At varius vel pharetra vel turpis. Ut pharetra sit amet aliquam id diam maecenas. Aliquam nulla facilisi cras fermentum odio eu. Ut venenatis tellus in metus. Mattis enim ut tellus elementum sagittis vitae et. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Eu nisl nunc mi ipsum faucibus vitae aliquet. Egestas sed tempus urna et pharetra. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Dictum varius duis at consectetur lorem donec massa sapien. Faucibus nisl tincidunt eget nullam.

Nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Sit amet consectetur adipiscing elit pellentesque. Lobortis mattis aliquam faucibus purus in massa tempor nec. Tellus in metus vulputate eu scelerisque. Integer eget aliquet nibh praesent tristique magna sit amet. Tortor at auctor urna nunc id. Aenean vel elit scelerisque mauris. Eleifend donec pretium vulputate sapien nec sagittis. Semper quis lectus nulla at. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Sit amet porttitor eget dolor morbi.

Donec pretium vulputate sapien nec sagittis. Arcu bibendum at varius vel. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Nunc lobortis mattis aliquam faucibus purus. Eget mauris pharetra et ultrices neque ornare aenean euismod. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. In hendrerit gravida rutrum quisque non tellus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Tincidunt eget nullam non nisi est sit amet facilisis magna. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Quis viverra nibh cras pulvinar mattis.


</body>

</html>
